<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ8zy3KK\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ8zy3KK/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ8zy3KK.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ8zy3KK\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZ8zy3KK\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Z8zy3KK',
    'container.build_id' => 'f6e396ac',
    'container.build_time' => 1550438091,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ8zy3KK');
